{"uuid": "61f6ef46-55bd-4f28-80fc-d966c35f9af1", "children": ["22c86be7-d6a4-4c85-86df-ba7c580dedeb"], "befores": [{"name": "register_user_and_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (750,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/conftest.py\", line 97, in register_user_and_login\n    login_page.login(register_data[1])\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/login_page.py\", line 53, in login\n    self.set_email_to_field(email)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/login_page.py\", line 25, in set_email_to_field\n    self.click_email_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/login_page.py\", line 19, in click_email_field\n    self.driver.find_element(*LoginPageLocators.EMAIL_FIELD).click()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Зарегистриовать пользователя", "status": "passed", "parameters": [{"name": "payload", "value": "{'name': 'Любовь4745', 'password': '222222', 'email': 'polonskaya2200@yandex.ru'}"}], "start": 1724130547919, "stop": 1724130548184}, {"name": "Войти в аккаунт", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class=\"text input__textfield text_type_main-default\" name=\"name\" type=\"text\"> is not clickable at point (750,385) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/login_page.py\", line 53, in login\n    self.set_email_to_field(email)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/login_page.py\", line 25, in set_email_to_field\n    self.click_email_field()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/pages/login_page.py\", line 19, in click_email_field\n    self.driver.find_element(*LoginPageLocators.EMAIL_FIELD).click()\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/polonskaya-ly/PycharmProjects/Diplom_3/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Открыть страницу \"Авторизации", "status": "passed", "start": 1724130548184, "stop": 1724130548485}], "parameters": [{"name": "email", "value": "'polonskaya2200@yandex.ru'"}], "start": 1724130548184, "stop": 1724130548501}], "start": 1724130547919, "stop": 1724130548501}], "start": 1724130547919, "stop": 1724130548522}